// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trip_Show_AgenciaDeViagens.Data;

namespace Trip_Show_AgenciaDeViagens.Migrations
{
    [DbContext(typeof(PassagemContext))]
    partial class PassagemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Trip_Show_AgenciaDeViagens.Models.Cliente", b =>
                {
                    b.Property<int>("ID_CLIENTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CIDADE_CLIENTE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("DATA_IDA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DATA_NASC")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DATA_VOLTA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("EMAIL_CLIENTE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ESTADO_CLIENTE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NOME_CLIENTE")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID_CLIENTE");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Trip_Show_AgenciaDeViagens.Models.Destino", b =>
                {
                    b.Property<int>("ID_DESTINO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CIDADE_DESTINO")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ESTADO_DESTINO")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PAIS_DESTINO")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("PRECO_DESTINO")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_DESTINO");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("Trip_Show_AgenciaDeViagens.Models.Passagem", b =>
                {
                    b.Property<int>("ID_PASSAGEM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteID_CLIENTE")
                        .HasColumnType("int");

                    b.Property<string>("DATA_COMPRA")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("DestinoID_DESTINO")
                        .HasColumnType("int");

                    b.HasKey("ID_PASSAGEM");

                    b.HasIndex("ClienteID_CLIENTE");

                    b.HasIndex("DestinoID_DESTINO");

                    b.ToTable("Passagens");
                });

            modelBuilder.Entity("Trip_Show_AgenciaDeViagens.Models.Passagem", b =>
                {
                    b.HasOne("Trip_Show_AgenciaDeViagens.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID_CLIENTE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trip_Show_AgenciaDeViagens.Models.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoID_DESTINO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Destino");
                });
#pragma warning restore 612, 618
        }
    }
}
