// <auto-generated />
using AgenciaViagensMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgenciaViagensMVC.Migrations.Cliente
{
    [DbContext(typeof(ClienteContext))]
    [Migration("20211213190436_Second Creation")]
    partial class SecondCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgenciaViagensMVC.Models.Cliente", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CidadeOrigem")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("DataIda")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("DataNasc")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Datavolta")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("EstadoOrigem")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("nome_cliente")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IdPessoa");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
