USE [master]
GO
/****** Object:  Database [TripShow_AgenciaViagens]    Script Date: 15/12/2021 18:03:44 ******/
CREATE DATABASE [TripShow_AgenciaViagens]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TripShow_AgenciaViagens', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TripShow_AgenciaViagens.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TripShow_AgenciaViagens_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TripShow_AgenciaViagens_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TripShow_AgenciaViagens].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET ARITHABORT OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET RECOVERY FULL 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET  MULTI_USER 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TripShow_AgenciaViagens', N'ON'
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET QUERY_STORE = OFF
GO
USE [TripShow_AgenciaViagens]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 15/12/2021 18:03:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clientes]    Script Date: 15/12/2021 18:03:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clientes](
	[ID_CLIENTE] [int] IDENTITY(1,1) NOT NULL,
	[NOME_CLIENTE] [nvarchar](60) NOT NULL,
	[EMAIL_CLIENTE] [nvarchar](60) NOT NULL,
	[CIDADE_CLIENTE] [nvarchar](60) NOT NULL,
	[ESTADO_CLIENTE] [nvarchar](60) NOT NULL,
	[DATA_IDA] [nvarchar](15) NOT NULL,
	[DATA_VOLTA] [nvarchar](15) NOT NULL,
	[DATA_NASC] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED 
(
	[ID_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Destinos]    Script Date: 15/12/2021 18:03:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Destinos](
	[ID_DESTINO] [int] IDENTITY(1,1) NOT NULL,
	[CIDADE_DESTINO] [nvarchar](60) NOT NULL,
	[ESTADO_DESTINO] [nvarchar](60) NOT NULL,
	[PAIS_DESTINO] [nvarchar](60) NOT NULL,
	[PRECO_DESTINO] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Destinos] PRIMARY KEY CLUSTERED 
(
	[ID_DESTINO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Passagens]    Script Date: 15/12/2021 18:03:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Passagens](
	[ID_PASSAGEM] [int] IDENTITY(1,1) NOT NULL,
	[DATA_COMPRA] [nvarchar](15) NOT NULL,
	[ClienteID_CLIENTE] [int] NOT NULL,
	[DestinoID_DESTINO] [int] NOT NULL,
 CONSTRAINT [PK_Passagens] PRIMARY KEY CLUSTERED 
(
	[ID_PASSAGEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Passagens_ClienteID_CLIENTE]    Script Date: 15/12/2021 18:03:48 ******/
CREATE NONCLUSTERED INDEX [IX_Passagens_ClienteID_CLIENTE] ON [dbo].[Passagens]
(
	[ClienteID_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Passagens_DestinoID_DESTINO]    Script Date: 15/12/2021 18:03:48 ******/
CREATE NONCLUSTERED INDEX [IX_Passagens_DestinoID_DESTINO] ON [dbo].[Passagens]
(
	[DestinoID_DESTINO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Passagens]  WITH CHECK ADD  CONSTRAINT [FK_Passagens_Clientes_ClienteID_CLIENTE] FOREIGN KEY([ClienteID_CLIENTE])
REFERENCES [dbo].[Clientes] ([ID_CLIENTE])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Passagens] CHECK CONSTRAINT [FK_Passagens_Clientes_ClienteID_CLIENTE]
GO
ALTER TABLE [dbo].[Passagens]  WITH CHECK ADD  CONSTRAINT [FK_Passagens_Destinos_DestinoID_DESTINO] FOREIGN KEY([DestinoID_DESTINO])
REFERENCES [dbo].[Destinos] ([ID_DESTINO])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Passagens] CHECK CONSTRAINT [FK_Passagens_Destinos_DestinoID_DESTINO]
GO
USE [master]
GO
ALTER DATABASE [TripShow_AgenciaViagens] SET  READ_WRITE 
GO
